using System.Collections;
using System.Collections.Generic;

namespace RoSharp.Http
{
    /// <summary>
    /// Represents a response from the Roblox API through a RoSharp request with no further data provided by RoSharp.
    /// </summary>
    public class HttpResult
    {
        /// <summary>
        /// Gets the internal <see cref="HttpResponseMessage"/>.
        /// </summary>
        public HttpResponseMessage HttpResponse { get; internal set; }

        /// <inheritdoc/>
        public static implicit operator HttpResponseMessage(HttpResult response) => response.HttpResponse;

        internal HttpResult(HttpResponseMessage response)
        {
            HttpResponse = response;
        }
    }

    /// <summary>
    /// Represents a response from the Roblox API through a RoSharp request containing a data structure generated by RoSharp.
    /// </summary>
    public class HttpResult<T> : HttpResult
    {
        /// <summary>
        /// Gets the data provided by RoSharp.
        /// </summary>
        public T Value { get; internal set; }

        /// <inheritdoc/>
        public static implicit operator T(HttpResult<T> result) => result.Value;

        internal HttpResult(HttpResponseMessage response, T value) : base(response)
        {
            Value = value;
        }
    }
}
